# Pandas

In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.Series([0.25, 0.50, 0.75, 1.0])
data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

In [3]:
data.values

array([0.25, 0.5 , 0.75, 1.  ])

In [4]:
data.index

RangeIndex(start=0, stop=4, step=1)

In [5]:
data[1]

np.float64(0.5)

In [6]:
data[1:3]

1    0.50
2    0.75
dtype: float64

- pandas serilerinin indexlerini kendimiz tanımlayabiliriz index olarak sayılar veya  harfler kullanılabilir

In [7]:
data = pd.Series([0.25, 0.5, 0.75, 1.0], index =['a', 'b', 'c', 'd'])
data['a']

np.float64(0.25)

In [8]:
data = pd.Series([0.25, 0.5, 0.75, 1.0], index =[1, 4, 7, 2])
data[7]

np.float64(0.75)

###  Series as specialized dictionary

In [9]:
population_dict = {'California': 38332521,
                        'Texas': 26448193,
                     'New York': 19651127,
                      'Florida': 19552860,
                     'Illinois': 12882135}
population = pd.Series(population_dict)
population

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [10]:
type(population)

pandas.core.series.Series

In [11]:
population['California']

np.int64(38332521)

In [12]:
population['California':'Illinois']

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

### Constructing Series objects

In [13]:
pd.Series([2, 4, 6])

0    2
1    4
2    6
dtype: int64

In [14]:
pd.Series(5, index=[100, 200, 300])

100    5
200    5
300    5
dtype: int64

In [15]:
pd.Series({2:'a', 1:'b', 3:'c'})

2    a
1    b
3    c
dtype: object

In [16]:
pd.Series({2:'a', 1:'b', 3:'c'}, index=[3, 2])

3    c
2    a
dtype: object

In [17]:
area_dict = {'California': 423967, 'Texas': 695662, 'New York': 141297,
 'Florida': 170312, 'Illinois': 149995}

In [18]:
area = pd.Series(area_dict)
area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
dtype: int64

In [19]:
states = pd.DataFrame({'population': population, 'area': area }) # pd series i dataframe çevirme
states

            population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

In [20]:
states.index

Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')

In [21]:
states.columns

Index(['population', 'area'], dtype='object')

In [22]:
yaş = [23, 43, 12, 34, 56, 10]
saç_rengi = ['siyah', 'sarı', 'kumral', 'siyah', 'kızıl', 'sarı']
isim = ['Emre', 'Çınar', 'Kemal', 'Esma', 'Ceyda', 'Ali']

data1 = pd.DataFrame({'isim': isim, 'Yaş':yaş, 'saç_rengi':saç_rengi})
data1

    isim  Yaş saç_rengi
0   Emre   23     siyah
1  Çınar   43      sarı
2  Kemal   12    kumral
3   Esma   34     siyah
4  Ceyda   56     kızıl
5    Ali   10      sarı

###  DataFrame as specialized dictionary

In [23]:
states['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

### Constructing DataFrame objects

In [24]:
pd.DataFrame(population, columns=['population'])

            population
California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135

In [25]:
data = [{'a':i, 'b': 2*i} for i in range(3)]
pd.DataFrame(data)

   a  b
0  0  0
1  1  2
2  2  4

In [26]:
pd.DataFrame({'a':'a', 'b':2}, {'c':3, 'd':4})

   a  b
c  a  2
d  a  2

In [27]:
pd.DataFrame({
    'population': population, 
    'area': area
})

            population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

In [29]:
pd.DataFrame(
    np.random.rand(3,2),
    columns=['foo', 'bar'],
    index=['a', 'b', 'c']
)

        foo       bar
a  0.197420  0.716622
b  0.327725  0.068800
c  0.478593  0.876441

In [30]:
A = np.zeros(3, dtype=[('A', 'i8'), ('B', 'f8')])
A

array([(0, 0.), (0, 0.), (0, 0.)], dtype=[('A', '<i8'), ('B', '<f8')])

In [31]:
pd.DataFrame(A)

   A    B
0  0  0.0
1  0  0.0
2  0  0.0

### The Pandas Index Object

In [32]:
ind = pd.Index([2, 3, 5, 7, 11])
ind

Index([2, 3, 5, 7, 11], dtype='int64')

In [33]:
ind[1]

np.int64(3)

In [34]:
ind[::2]

Index([2, 5, 11], dtype='int64')

In [ ]:
print(ind.shape, ind.dtype, ind.ndim, ind.size) # shape verinin boyutu, dtype verinin tiğini, ndim kaç boyutlu veri, size toplam eleman sayısını verir

(5,) int64 1 5

In [ ]:
indA = pd.Index([1, 3, 5, 7, 9]) # Tek boyutlu etiketli dizi tek değişkenli veri tutmak zaman serisi oluşturmak vb işlemler için kullanılır
indB = pd.Index([2, 3, 5, 7, 11])

indA & indB

Index([0, 3, 5, 7, 9], dtype='int64')

In [37]:
indA | indB

Index([3, 3, 5, 7, 11], dtype='int64')

In [38]:
indA ^ indB

Index([3, 0, 0, 0, 2], dtype='int64')

### Data Selection in Series

In [39]:
data = pd.Series([0.25, 0.5, 0.75, 1.0], index = ['a', 'b', 'c', 'd'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [40]:
data['b']

np.float64(0.5)

In [41]:
'a' in data

True

In [42]:
data.keys()

Index(['a', 'b', 'c', 'd'], dtype='object')

In [43]:
list[data.items()]

list[<zip object at 0x000001CFF43CFD40>]

In [44]:
data['e'] = 1.25
data

a    0.25
b    0.50
c    0.75
d    1.00
e    1.25
dtype: float64

###  Series as one-dimensional array

In [45]:
data['a': 'c']

a    0.25
b    0.50
c    0.75
dtype: float64

In [46]:
data[0:2]

a    0.25
b    0.50
dtype: float64

In [47]:
data[(data > 0.3) & (data < 0.8)]

b    0.50
c    0.75
dtype: float64

In [48]:
data[['a', 'e']]

a    0.25
e    1.25
dtype: float64

###  Indexers: loc, iloc, and ix

In [49]:
data = pd.Series(['a', 'b', 'c'], index = [1, 3, 5])
data

1    a
3    b
5    c
dtype: object

In [50]:
data[1]

'a'

In [51]:
data[1:3]

3    b
5    c
dtype: object

.loc  index ve kolon adına göre veri seçer
.iloc numaraya göre seçer 0 dan başlayan sıra numarasına göre seçer

benzetme : bir apartman düşün loc = daire numarasına göre çağırmak "A-5 numaralı daire", iloc = sıraya göre çağırmak "soldan 3. daire"

In [ ]:
data.loc[1]

'a'

In [53]:
data.loc[1:3]

1    a
3    b
dtype: object

In [54]:
data.iloc[1]

'b'

In [55]:
data.iloc[1:3]

3    b
5    c
dtype: object

### Data Selection in DataFrame

In [57]:
area = pd.Series({'California': 423967, 'Texas': 695662,
 'New York': 141297, 'Florida': 170312,
 'Illinois': 149995})

pop = pd.Series({'California': 38332521, 'Texas': 26448193,
 'New York': 19651127, 'Florida': 19552860,
 'Illinois': 12882135})

data = pd.DataFrame({'area': area, 'pop': pop})
data

              area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

In [58]:
data['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [59]:
data.area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [60]:
data.area is data['area']

True

In [61]:
data.pop is data['pop']

False

In [62]:
data['density'] = data['pop'] / data['area']

In [63]:
data

              area       pop     density
California  423967  38332521   90.413926
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

### DataFrame as two-dimensional array

In [64]:
data.values

array([[4.23967000e+05, 3.83325210e+07, 9.04139261e+01],
       [6.95662000e+05, 2.64481930e+07, 3.80187404e+01],
       [1.41297000e+05, 1.96511270e+07, 1.39076746e+02],
       [1.70312000e+05, 1.95528600e+07, 1.14806121e+02],
       [1.49995000e+05, 1.28821350e+07, 8.58837628e+01]])

In [ ]:
data.T  # taranspoz almak satırları sütuna sütunları satıra çevirmek

           California         Texas      New York       Florida      Illinois
area     4.239670e+05  6.956620e+05  1.412970e+05  1.703120e+05  1.499950e+05
pop      3.833252e+07  2.644819e+07  1.965113e+07  1.955286e+07  1.288214e+07
density  9.041393e+01  3.801874e+01  1.390767e+02  1.148061e+02  8.588376e+01

In [66]:
data.values[0]

array([4.23967000e+05, 3.83325210e+07, 9.04139261e+01])

In [67]:
data['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [68]:
data.iloc[:3, :2]

              area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127

In [69]:
data.loc[:'Illinois', :'pop']

              area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

In [71]:
data.loc[data.density > 100 , ['pop', 'density']]

               pop     density
New York  19651127  139.076746
Florida   19552860  114.806121

In [72]:
data.iloc[0, 2] = 90
data

              area       pop     density
California  423967  38332521   90.000000
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

### Index Preservation

In [73]:
rng = np.random.RandomState(42)
ser = pd.Series(rng.randint(0, 10, 4))
ser

0    6
1    3
2    7
3    4
dtype: int32

In [74]:
df = pd.DataFrame(rng.randint(0, 10, (3, 4)), columns=['A', 'B', 'C', 'D'])
df

   A  B  C  D
0  6  9  2  6
1  7  4  3  7
2  7  2  5  4

In [75]:
np.exp(ser)

0     403.428793
1      20.085537
2    1096.633158
3      54.598150
dtype: float64

In [76]:
np.sin(df * np.pi / 4)

          A             B         C             D
0 -1.000000  7.071068e-01  1.000000 -1.000000e+00
1 -0.707107  1.224647e-16  0.707107 -7.071068e-01
2 -0.707107  1.000000e+00 -0.707107  1.224647e-16

### Index Alignment

In [77]:
area = pd.Series({'Alaska': 1723337, 'Texas': 695662,
 'California': 423967}, name='area')
population = pd.Series({'California': 38332521, 'Texas': 26448193,
 'New York': 19651127}, name='population')

In [78]:
population / area

Alaska              NaN
California    90.413926
New York            NaN
Texas         38.018740
dtype: float64

In [82]:
A = pd.Series([2, 4, 6], index =[0, 1, 2])
B = pd.Series([1, 3, 5], index=[1, 2, 3])
A+B

0    NaN
1    5.0
2    9.0
3    NaN
dtype: float64

In [83]:
A.add(B, fill_value=0)

0    2.0
1    5.0
2    9.0
3    5.0
dtype: float64

In [84]:
A = pd.DataFrame(rng.randint(0, 20, (2, 2)), columns=list('AB'))
A

   A   B
0  1  11
1  5   1

In [86]:
B = pd.DataFrame(rng.randint(0, 10, (3,3)), columns=list('BAC'))

In [90]:
A

   A   B
0  1  11
1  5   1

In [87]:
B

   B  A  C
0  3  8  2
1  4  2  6
2  4  8  6

In [88]:
A+B

     A     B   C
0  9.0  14.0 NaN
1  7.0   5.0 NaN
2  NaN   NaN NaN

In [ ]:
fill = A.stack().mean() # stack() sütunları satıra çeviri
A.add(B, fill_value=fill) # add() "+" operatörünün akıllı halidir ortak indise sahip değerleri toplar ör A için    1+8 = 9, B için 8+11 = 14

      A     B     C
0   9.0  14.0   6.5
1   7.0   5.0  10.5
2  12.5   8.5  10.5

### Operations Between DataFrame and Series

In [91]:
A  = rng.randint(10, size=(3, 4))
A

array([[1, 3, 8, 1],
       [9, 8, 9, 4],
       [1, 3, 6, 7]], dtype=int32)

In [ ]:
A - A[0] # 0. satırı tüm satırlardan çıkarır

array([[ 0,  0,  0,  0],
       [ 8,  5,  1,  3],
       [ 0,  0, -2,  6]], dtype=int32)

In [93]:
df = pd.DataFrame(A, columns=list('QRST'))
df - df.iloc[0]

   Q  R  S  T
0  0  0  0  0
1  8  5  1  3
2  0  0 -2  6

In [ ]:
df.subtract(df['R'], axis=0) # sayısal verilerde çıkarma işlemi yapar (index e göre hizayalarak)

   Q  R  S  T
0 -2  0  5 -2
1  1  0  1 -4
2 -2  0  3  4

In [95]:
halfrow = df.iloc[0, ::2]
halfrow

Q    1
S    8
Name: 0, dtype: int32

In [96]:
df - halfrow

     Q   R    S   T
0  0.0 NaN  0.0 NaN
1  8.0 NaN  1.0 NaN
2  0.0 NaN -2.0 NaN