##  Handling Missing Data

In [1]:
import numpy as np
import pandas as pd

In [2]:
vals1 = np.array([1, None, 3, 4])
vals1

array([1, None, 3, 4], dtype=object)

In [3]:
for dtype in ['object', 'int']:
    print('dtype=', dtype)
    %timeit np.arange(1E6, dtype=dtype).sum()
    print

dtype= object
42.6 ms ± 4.6 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
dtype= int
2.98 ms ± 432 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [6]:
vals2 = np.array([1, np.nan, 3, 4])
print(vals2)
print(vals2.dtype)

[ 1. nan  3.  4.]
float64

In [7]:
1 + np.nan

nan

In [8]:
0 * np.nan

nan

In [11]:
print(vals2.sum(), vals2.max(), vals2.min())

nan nan nan

In [12]:
print(np.nansum(vals2),np.nanmax(vals2), np.nanmin(vals2))

8.0 4.0 1.0

In [13]:
pd.Series([1, np.nan, None, 4])

0    1.0
1    NaN
2    NaN
3    4.0
dtype: float64

In [14]:
x = pd.Series(range(2), dtype=int)
x

0    0
1    1
dtype: int64

In [15]:
x[0] = None

In [16]:
x

0    NaN
1    1.0
dtype: float64

In [17]:
data = pd.Series([1, np.nan, 'Heloo', None])
data.isnull()

0    False
1     True
2    False
3     True
dtype: bool

In [18]:
data[data.notnull()]

0        1
2    Heloo
dtype: object

In [19]:
data.dropna()

0        1
2    Heloo
dtype: object

In [25]:
df = pd.DataFrame([[1, np.nan, 2],
                    [2,     3, 5], 
                    [np.nan, 4, 6]],)
df

     0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [ ]:
df.dropna() # eksik değer olan satırları atar

     0    1  2
1  2.0  3.0  5

In [ ]:
df.dropna(axis='columns') # eksik değer içeren sütunları atar

   2
0  2
1  5
2  6

In [26]:
df[3] = np.nan
df

     0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  6 NaN

In [30]:
df.dropna(axis='columns', how='all')

     0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [31]:
df.dropna(axis='rows', thresh=3)

     0    1  2   3
1  2.0  3.0  5 NaN

In [32]:
data = pd.Series([1, np.nan, None, 4], index=list('abcd'))
data

a    1.0
b    NaN
c    NaN
d    4.0
dtype: float64

In [33]:
data.fillna(0)

a    1.0
b    0.0
c    0.0
d    4.0
dtype: float64

In [34]:
data.fillna(method='ffill')

C:\Users\İlyas\AppData\Local\Temp\ipykernel_17752\1844443866.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data.fillna(method='ffill')

a    1.0
b    1.0
c    1.0
d    4.0
dtype: float64

In [35]:
data.fillna(method='bfill')

C:\Users\İlyas\AppData\Local\Temp\ipykernel_17752\1397359497.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data.fillna(method='bfill')

a    1.0
b    4.0
c    4.0
d    4.0
dtype: float64

In [37]:
df

     0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  6 NaN

In [47]:
df.fillna(method='ffill', axis=1)

C:\Users\İlyas\AppData\Local\Temp\ipykernel_17752\901808322.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill', axis=1)

     0    1    2    3
0  1.0  1.0  2.0  2.0
1  2.0  3.0  5.0  5.0
2  NaN  4.0  6.0  6.0

### Hierarchical Indexing

In [2]:
import numpy as np
import pandas as pd

In [4]:
index = [('California', 2000), ('California', 2010),('New York', 2000), ('New York', 2010), ('Texas', 2000), ('Texas', 2010)] 
populations = [33871648, 37253956, 18976457, 19378102, 20851820, 25145561]

pop = pd.Series(populations, index  = index)
pop

(California, 2000)    33871648
(California, 2010)    37253956
(New York, 2000)      18976457
(New York, 2010)      19378102
(Texas, 2000)         20851820
(Texas, 2010)         25145561
dtype: int64

In [5]:
pop[('California', 2010):('Texas', 2000)]

(California, 2010)    37253956
(New York, 2000)      18976457
(New York, 2010)      19378102
(Texas, 2000)         20851820
dtype: int64

In [ ]:
pop[[i for i in pop.index if i[1]==2010]] # böyle istenen belirli kısımlar alınabilir ama büyük veri setleri için mantıklı değil

(California, 2010)    37253956
(New York, 2010)      19378102
(Texas, 2010)         25145561
dtype: int64

In [7]:
# çoklu indexleme

index = pd.MultiIndex.from_tuples(index)
index

MultiIndex([('California', 2000),
            ('California', 2010),
            (  'New York', 2000),
            (  'New York', 2010),
            (     'Texas', 2000),
            (     'Texas', 2010)],
           )

In [8]:
pop = pop.reindex(index)
pop

California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [9]:
pop[:, 2010]

California    37253956
New York      19378102
Texas         25145561
dtype: int64

In [ ]:
pop_df = pop.unstack() # unstack() çok indexli bir yapıyı DataFrame haline getirmeye yarar
pop_df

                2000      2010
California  33871648  37253956
New York    18976457  19378102
Texas       20851820  25145561

In [18]:
pop_df = pd.DataFrame({'total':pop,
                       'under18': [9267089, 9284094,
4687374, 4318033,
5906301, 6879014]})

In [19]:
pop_df

                    total  under18
California 2000  33871648  9267089
           2010  37253956  9284094
New York   2000  18976457  4687374
           2010  19378102  4318033
Texas      2000  20851820  5906301
           2010  25145561  6879014

- unstack() sadece DataFrame üzerinde veya Series üzerinde çalışıyor bir reshape metodu ve çok indexli verilerde kullanılıyor aşağdaki gibi indexsi sütun haline getiriyor

In [20]:
f_u18 = pop_df['under18'] / pop_df['total']
f_u18.unstack()

                2000      2010
California  0.273594  0.249211
New York    0.247010  0.222831
Texas       0.283251  0.273568

In [21]:
df = pd.DataFrame(np.random.rand(4, 2),
                  index=[['a', 'a', 'b', 'b'],
                          [1, 2, 1, 2]],
                  columns=['data1', 'data2'])
df

        data1     data2
a 1  0.247589  0.118355
  2  0.297572  0.800323
b 1  0.457750  0.038280
  2  0.685055  0.661276

In [22]:
df.unstack()

      data1               data2
          1         2         1         2
a  0.247589  0.297572  0.118355  0.800323
b  0.457750  0.685055  0.038280  0.661276

In [29]:
pd.MultiIndex.from_arrays([['a', 'a', 'b', 'b'], [1, 2, 1, 2]])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2)],
           )

In [30]:
pd.MultiIndex.from_tuples([('a', 1), ('a', 2), ('b', 1), ('b', 2)])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2)],
           )

In [31]:
pd.MultiIndex.from_product([['a', 'b'], [1, 2]])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2)],
           )

### Indexing and Slicing a MultiIndex

In [33]:
pop['California', 2000]

np.int64(33871648)

In [34]:
pop['California']

2000    33871648
2010    37253956
dtype: int64

In [37]:
pop.loc['California': 'New York']

California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
dtype: int64

In [38]:
pop[:, 2000]

California    33871648
New York      18976457
Texas         20851820
dtype: int64

In [39]:
pop[pop>22000000]

California  2000    33871648
            2010    37253956
Texas       2010    25145561
dtype: int64

In [40]:
pop[['California', 'Texas']]

California  2000    33871648
            2010    37253956
Texas       2000    20851820
            2010    25145561
dtype: int64

- çoklu index dilimleme işlemlerinin çoğu index sıralı değil ise başarısıs olur

In [51]:
index = pd.MultiIndex.from_product([['a', 'c', 'd'], [1, 2]])
data_ = pd.Series(np.random.rand(6), index=index)
data.index.names = ['char', 'int']
data_

a  1    0.332406
   2    0.568264
c  1    0.739705
   2    0.292228
d  1    0.389765
   2    0.818499
dtype: float64

In [52]:
try:
    data_['a': 'b'] # eğer belirli bir kısmını almaya çalışırsak hata alırız
except KeyError as e:
    print(e)

In [50]:
data = data.sort_index() # indexler bu şekilde sıralandığında kısmi dilimleme çalışır
data

char  int
a     1      0.359278
      2      0.659861
c     1      0.019356
      2      0.041415
d     1      0.576911
      2      0.895832
dtype: float64

In [46]:
data['a': 'b']

char  int
a     1      0.254954
      2      0.519544
dtype: float64

### Stacking and unstacking indices

In [54]:
pop.unstack(level=0)

      California  New York     Texas
2000    33871648  18976457  20851820
2010    37253956  19378102  25145561

In [55]:
pop.unstack(level=1)

                2000      2010
California  33871648  37253956
New York    18976457  19378102
Texas       20851820  25145561

In [58]:
# unstack ın tersi stack tır eski veriyi geri kazanmak için kullanılabilir
pop.unstack().stack()

California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64