### Pivot Tables

In [5]:
import numpy as np
import pandas as pd
import seaborn as sns

titanic = sns.load_dataset('titanic')
import warnings
warnings.filterwarnings('ignore')

In [2]:
titanic.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [12]:
titanic.groupby('sex')['survived'].sum()

sex
female    233
male      109
Name: survived, dtype: int64

In [13]:
titanic.groupby('class')['survived'].sum()

class
First     136
Second     87
Third     119
Name: survived, dtype: int64

In [14]:
titanic.groupby(['sex', 'class'])['survived'].aggregate('mean').unstack() # kod sex ve class a göre guruplama yapıyor ve bunu survived değişkeni üzerinden aggregate komutunu kullanarak ortalama üzerinden ölçüyor
# indexlemenin doğru olması için unstack() kullanılır bu sayede satırlar sex sütunlar class olur

class      First    Second     Third
sex
female  0.968085  0.921053  0.500000
male    0.368852  0.157407  0.135447

In [ ]:
titanic.pivot_table('survived', index='sex', columns='class') # üstte olan şeyin aynısını yapıyor 
# parametre ile ölçümü değiştirebiliyorsun burada ortalama kullanılmış aggfunc = '' ile sum, count, median kullanabilirsin

class      First    Second     Third
sex
female  0.968085  0.921053  0.500000
male    0.368852  0.157407  0.135447

In [ ]:
age = pd.cut(titanic['age'], [0, 18, 80])
titanic.pivot_table('survived', ['sex', age], 'class') # burada pd.cut ile ki bu sürekli değişkenleri belirli aralıklara bölmemizi sağlar yaş değişkenini belirli aralıklara böldükten sonra diğer değişkenler ile gurupluyoruz

class               First    Second     Third
sex    age
female (0, 18]   0.909091  1.000000  0.511628
       (18, 80]  0.972973  0.900000  0.423729
male   (0, 18]   0.800000  0.600000  0.215686
       (18, 80]  0.375000  0.071429  0.133663

In [ ]:
fare = pd.qcut(titanic['fare'], 3)    # pd.cut tan farklı olarak burada aralıklar verinin dağılımına göre otomatik oluşur sadece kaç aralık girmek istediğini yazarsın
titanic.pivot_table('survived', ['sex', age], [fare, 'class']) # (ölçüm değişkeni, satırlar, sütunlar)

fare            (-0.001, 8.662]           (8.662, 26.0]                      \
class                     First     Third         First    Second     Third
sex    age
female (0, 18]              NaN  0.700000           NaN  1.000000  0.583333
       (18, 80]             NaN  0.523810           1.0  0.877551  0.433333
male   (0, 18]              NaN  0.166667           NaN  0.500000  0.500000
       (18, 80]             0.0  0.127389           0.0  0.086957  0.102564

fare            (26.0, 512.329]
class                     First Second     Third
sex    age
female (0, 18]         0.909091    1.0  0.111111
       (18, 80]        0.972222    1.0  0.125000
male   (0, 18]         0.800000    0.8  0.052632
       (18, 80]        0.400000    0.0  0.500000

In [20]:
titanic.pivot_table(index='sex', columns='class', aggfunc={'survived':sum, 'fare':'mean'})

              fare                       survived
class        First     Second      Third    First Second Third
sex
female  106.125798  21.970121  16.118810       91     70    72
male     67.226127  19.741782  12.661633       45     17    47

In [21]:
titanic.pivot_table('survived', index  = 'sex', columns='class', margins=True)

class      First    Second     Third       All
sex
female  0.968085  0.921053  0.500000  0.742038
male    0.368852  0.157407  0.135447  0.188908
All     0.629630  0.472826  0.242363  0.383838

### Dates and Times in Python

In [23]:
from datetime import datetime
datetime(year=2015, month=7, day=4)

datetime.datetime(2015, 7, 4, 0, 0)

In [24]:
from dateutil import parser
date = parser.parser("4th of July, 2015")
date

In [26]:
date = np.array('2015-07-04', dtype=np.datetime64)
date

array('2015-07-04', dtype='datetime64[D]')

In [27]:
date + np.arange(12)

array(['2015-07-04', '2015-07-05', '2015-07-06', '2015-07-07',
       '2015-07-08', '2015-07-09', '2015-07-10', '2015-07-11',
       '2015-07-12', '2015-07-13', '2015-07-14', '2015-07-15'],
      dtype='datetime64[D]')

In [29]:
date = pd.to_datetime("4th of July, 2015")
date

Timestamp('2015-07-04 00:00:00')

In [30]:
date.strftime('%A')

'Saturday'

In [31]:
date + pd.to_timedelta(np.arange(12), 'D')

DatetimeIndex(['2015-07-04', '2015-07-05', '2015-07-06', '2015-07-07',
               '2015-07-08', '2015-07-09', '2015-07-10', '2015-07-11',
               '2015-07-12', '2015-07-13', '2015-07-14', '2015-07-15'],
              dtype='datetime64[ns]', freq=None)

### Pandas Time Series: Indexing by Time

In [32]:
index = pd.DatetimeIndex(['2014-07-04', '2014-08-04','2015-07-04', '2015-08-04'])
data = pd.Series([0, 1, 2, 3], index = index)
data

2014-07-04    0
2014-08-04    1
2015-07-04    2
2015-08-04    3
dtype: int64

In [33]:
data['2014-07-04':'2015-07-04']

2014-07-04    0
2014-08-04    1
2015-07-04    2
dtype: int64

In [34]:
data['2015']

2015-07-04    2
2015-08-04    3
dtype: int64

In [35]:
data['2014']

2014-07-04    0
2014-08-04    1
dtype: int64

In [41]:
dates = pd.to_datetime([datetime(2015, 7, 3), '4th of July, 2015','2015-Jul-6', '07-07-2015', '20150708'])
index = range(5)
pd.DataFrame(dates, index=index)

           0
0 2015-07-03
1 2015-07-04
2 2015-07-06
3 2015-07-07
4 2015-07-08

In [42]:
dates.to_period('D')

PeriodIndex(['2015-07-03', '2015-07-04', '2015-07-06', '2015-07-07',
             '2015-07-08'],
            dtype='period[D]')

In [43]:
dates - dates[0]

TimedeltaIndex(['0 days', '1 days', '3 days', '4 days', '5 days'], dtype='timedelta64[ns]', freq=None)

In [ ]:
pd.date_range('2015-07-03', '2015-07-10') # verdiğimiz aralık içinde aralıklar dahil olmak üzere tarihler oluşturur

DatetimeIndex(['2015-07-03', '2015-07-04', '2015-07-05', '2015-07-06',
               '2015-07-07', '2015-07-08', '2015-07-09', '2015-07-10'],
              dtype='datetime64[ns]', freq='D')

In [45]:
pd.date_range('2015-07-03', periods=8)

DatetimeIndex(['2015-07-03', '2015-07-04', '2015-07-05', '2015-07-06',
               '2015-07-07', '2015-07-08', '2015-07-09', '2015-07-10'],
              dtype='datetime64[ns]', freq='D')

In [46]:
pd.date_range('2015-07-03', periods=8, freq='H')

DatetimeIndex(['2015-07-03 00:00:00', '2015-07-03 01:00:00',
               '2015-07-03 02:00:00', '2015-07-03 03:00:00',
               '2015-07-03 04:00:00', '2015-07-03 05:00:00',
               '2015-07-03 06:00:00', '2015-07-03 07:00:00'],
              dtype='datetime64[ns]', freq='h')

In [47]:
pd.date_range('2015-07-03', periods=8, freq='M')

DatetimeIndex(['2015-07-31', '2015-08-31', '2015-09-30', '2015-10-31',
               '2015-11-30', '2015-12-31', '2016-01-31', '2016-02-29'],
              dtype='datetime64[ns]', freq='ME')

In [48]:
pd.timedelta_range(0, periods=10, freq='H')

TimedeltaIndex(['0 days 00:00:00', '0 days 01:00:00', '0 days 02:00:00',
                '0 days 03:00:00', '0 days 04:00:00', '0 days 05:00:00',
                '0 days 06:00:00', '0 days 07:00:00', '0 days 08:00:00',
                '0 days 09:00:00'],
               dtype='timedelta64[ns]', freq='h')

In [49]:
pd.timedelta_range(0, periods=9, freq="2H30T")

TimedeltaIndex(['0 days 00:00:00', '0 days 02:30:00', '0 days 05:00:00',
                '0 days 07:30:00', '0 days 10:00:00', '0 days 12:30:00',
                '0 days 15:00:00', '0 days 17:30:00', '0 days 20:00:00'],
               dtype='timedelta64[ns]', freq='150min')