In [134]:
import numpy as np
import pandas as pd

In [135]:
print(pd.__version__)

2.2.3

In [136]:
# pandas serisi puşturma
s1 = pd.Series([10, 20, 30, 40, 50])
print(s1)

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [137]:
# numpy dizisinden pd serisi oluşturma

s2 = pd.Series(np.array([1, 2, 3, 4, 5]))
print(s2)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [138]:
# sözlükten seri oluşturma

soz = {'İstanbul' : 15000000, 'Ankara':5000000, 'İzmir':4000000}
s3 = pd.Series(soz)
print(s3)

İstanbul    15000000
Ankara       5000000
İzmir        4000000
dtype: int64

In [139]:
s4 = pd.Series(100, index=['a', 'b', 'c', 'd', 'e'])
print(s4)

a    100
b    100
c    100
d    100
e    100
dtype: int64

In [140]:
s = pd.Series([10, 20, 30, 40, 50], index=['a', 'b', 'c', 'd', 'e'])
print(s[0])
print(s.iloc[0])

10
10

C:\Users\İlyas\AppData\Local\Temp\ipykernel_12384\3283049551.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(s[0])

In [141]:
print(s['a'])
print(s.loc['a'])

10
10

In [142]:
print(s[[0, 2, 4]])
print(s.iloc[[0, 2, 4]])

a    10
c    30
e    50
dtype: int64
a    10
c    30
e    50
dtype: int64

C:\Users\İlyas\AppData\Local\Temp\ipykernel_12384\4257144492.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(s[[0, 2, 4]])

In [143]:
# dilimleme
s['a':'c']

a    10
b    20
c    30
dtype: int64

In [144]:
# boolean indexing
s[s > 25]

c    30
d    40
e    50
dtype: int64

In [145]:
# pd series özellikleri
s = pd.Series([10, 20, 30, 40, 50], index = ['a', 'b', 'c', 'd', 'e'])
print(s)

a    10
b    20
c    30
d    40
e    50
dtype: int64

In [146]:
print(s.index) # index
print(s.values) # değer
print(s.dtype) # veri tipi
print(s.size) # boyut
print(s.shape) # şekil

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')
[10 20 30 40 50]
int64
5
(5,)

In [147]:
s.name = 'şehir nüfusu'
s.index.name = 'şehirler'
s

şehirler
a    10
b    20
c    30
d    40
e    50
Name: şehir nüfusu, dtype: int64

In [148]:
# sölükten df oluşturma

veri = {
    'Ad' : ['Ali', 'Betül', 'Cemal', 'Deniz', 'Elif'],
    'Yaş': [25, 30, 35, 28, 32],
    'Maaş': [3000, 4000, 5000, 3500, 4500],
    'Şehir' : ['İstanbul', 'Ankara', 'İzmir', 'Bursa', 'Gaziantep']
}
df = pd.DataFrame(veri)

In [149]:
df

      Ad  Yaş  Maaş      Şehir
0    Ali   25  3000   İstanbul
1  Betül   30  4000     Ankara
2  Cemal   35  5000      İzmir
3  Deniz   28  3500      Bursa
4   Elif   32  4500  Gaziantep

In [150]:
veriler = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
df2 = pd.DataFrame(veriler, columns = ['A', 'B', 'C'])
df2

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

In [151]:
df = pd.DataFrame({
    'Ad': ['Ali', 'Betül', 'Cemal'], 
    'Yaş': [25, 30, 35],
    'Maaş': [3000, 4000, 5000]
})
print(df)

      Ad  Yaş  Maaş
0    Ali   25  3000
1  Betül   30  4000
2  Cemal   35  5000

In [152]:
# sütun erişimi
df['Ad']

0      Ali
1    Betül
2    Cemal
Name: Ad, dtype: object

In [153]:
#birden fazla sütun
df[['Ad', 'Maaş']]

      Ad  Maaş
0    Ali  3000
1  Betül  4000
2  Cemal  5000

In [154]:
#satır erişimi
df.iloc[0]

Ad       Ali
Yaş       25
Maaş    3000
Name: 0, dtype: object

In [155]:
df.loc[0]

Ad       Ali
Yaş       25
Maaş    3000
Name: 0, dtype: object

In [156]:
# Belirli hücre
print(df.loc[0, 'Ad'])

Ali

In [157]:
df.iloc[0, 0]

'Ali'

In [158]:
#çoklu satır
df.loc[0:2]

      Ad  Yaş  Maaş
0    Ali   25  3000
1  Betül   30  4000
2  Cemal   35  5000

In [159]:
df.iloc[0:2]

      Ad  Yaş  Maaş
0    Ali   25  3000
1  Betül   30  4000

In [160]:
df = pd.DataFrame({
'Ad': ['Ali', 'Betül', 'Cemal', 'Deniz'],
'Yaş': [25, 30, 35, 28],
'Maaş': [3000, 4000, 5000, 3500],
'Şehir': ['İstanbul', 'Ankara', 'İzmir', 'Bursa']
})
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Ad      4 non-null      object
 1   Yaş     4 non-null      int64
 2   Maaş    4 non-null      int64
 3   Şehir   4 non-null      object
dtypes: int64(2), object(2)
memory usage: 260.0+ bytes

In [161]:
df.describe()

             Yaş         Maaş
count   4.000000     4.000000
mean   29.500000  3875.000000
std     4.203173   853.912564
min    25.000000  3000.000000
25%    27.250000  3375.000000
50%    29.000000  3750.000000
75%    31.250000  4250.000000
max    35.000000  5000.000000

In [162]:
print(df.shape)
print(df.ndim)
print(df.columns)
print(df.index)
print(df.dtypes)

(4, 4)
2
Index(['Ad', 'Yaş', 'Maaş', 'Şehir'], dtype='object')
RangeIndex(start=0, stop=4, step=1)
Ad       object
Yaş       int64
Maaş      int64
Şehir    object
dtype: object

In [163]:
df.sample()  # rastgele satır göster

      Ad  Yaş  Maaş   Şehir
1  Betül   30  4000  Ankara

In [164]:
df.sample(n=4) # 4 rastgele satır

      Ad  Yaş  Maaş     Şehir
1  Betül   30  4000    Ankara
2  Cemal   35  5000     İzmir
0    Ali   25  3000  İstanbul
3  Deniz   28  3500     Bursa

In [165]:
df_kopya = df.copy()

In [166]:
# Benzersiz değerler
df['Şehir'].unique()

array(['İstanbul', 'Ankara', 'İzmir', 'Bursa'], dtype=object)

In [167]:
# Benzersiz değer sayısı
df['Şehir'].nunique()

4

In [168]:
df['Şehir'].value_counts() # değer sayıları

Şehir
İstanbul    1
Ankara      1
İzmir       1
Bursa       1
Name: count, dtype: int64

In [169]:
df = pd.DataFrame({
    'Ad': ['Ali', 'Betül', 'Cemal', 'Deniz', 'Elif'],
    'Yaş': [25, 30, 35, 28, 32],
    'Maaş': [3000, 4000, 5000, 3500, 4500]
})
df

      Ad  Yaş  Maaş
0    Ali   25  3000
1  Betül   30  4000
2  Cemal   35  5000
3  Deniz   28  3500
4   Elif   32  4500

In [170]:
df['Ad']

0      Ali
1    Betül
2    Cemal
3    Deniz
4     Elif
Name: Ad, dtype: object

In [171]:
df[['Ad', 'Yaş']]

      Ad  Yaş
0    Ali   25
1  Betül   30
2  Cemal   35
3  Deniz   28
4   Elif   32

In [172]:
df[0:3]

      Ad  Yaş  Maaş
0    Ali   25  3000
1  Betül   30  4000
2  Cemal   35  5000

In [173]:
# Boolean maskeleme
df[df['Yaş'] > 28]

      Ad  Yaş  Maaş
1  Betül   30  4000
2  Cemal   35  5000
4   Elif   32  4500

In [174]:
# çoklu koşul
df[(df['Yaş'] >28) & (df['Maaş'] > 3500)]

      Ad  Yaş  Maaş
1  Betül   30  4000
2  Cemal   35  5000
4   Elif   32  4500

In [175]:
# OR
df[(df['Yaş'] < 26) | (df['Yaş'] > 32)]

      Ad  Yaş  Maaş
0    Ali   25  3000
2  Cemal   35  5000

In [176]:
# NOT
df[~(df['Yaş'] > 30)]

      Ad  Yaş  Maaş
0    Ali   25  3000
1  Betül   30  4000
3  Deniz   28  3500

In [177]:
df[df['Ad'].isin(['Ali', 'Betül', 'Cemal'])]

      Ad  Yaş  Maaş
0    Ali   25  3000
1  Betül   30  4000
2  Cemal   35  5000

In [178]:
# Belirli hücre
df.at[0, 'Ad']

'Ali'

In [179]:
df.iat[0, 0]

'Ali'

In [180]:
# Belirli satırlar ve sütunlar
print(df.loc[1:3, ['Ad', 'Maaş']])
print(df.iloc[1:3, [0, 2]])

      Ad  Maaş
1  Betül  4000
2  Cemal  5000
3  Deniz  3500
      Ad  Maaş
1  Betül  4000
2  Cemal  5000

In [181]:
df = pd.DataFrame({
'İsim': ['Ali', 'Betül', 'Cemal', 'Deniz', 'Elif'],
'Yaş': [25, 30, 35, 28, 32],
'Maaş': [3000, 4000, 5000, 3500, 4500],
'Departman': ['IT', 'HR', 'IT', 'Finance', 'HR']
})
df

    İsim  Yaş  Maaş Departman
0    Ali   25  3000        IT
1  Betül   30  4000        HR
2  Cemal   35  5000        IT
3  Deniz   28  3500   Finance
4   Elif   32  4500        HR

In [182]:
df.isnull()

    İsim    Yaş   Maaş  Departman
0  False  False  False      False
1  False  False  False      False
2  False  False  False      False
3  False  False  False      False
4  False  False  False      False

In [183]:
df.isnull().sum()

İsim         0
Yaş          0
Maaş         0
Departman    0
dtype: int64

In [184]:
# eksik veri bulunan satırları görme
df[df.isnull().any(axis=1)]

Empty DataFrame
Columns: [İsim, Yaş, Maaş, Departman]
Index: []

In [185]:
df_temiz = df.dropna() # eksik veri satrılarını silme 
df_temiz

    İsim  Yaş  Maaş Departman
0    Ali   25  3000        IT
1  Betül   30  4000        HR
2  Cemal   35  5000        IT
3  Deniz   28  3500   Finance
4   Elif   32  4500        HR

In [186]:
df_temiz = df.dropna(how='all')
df_temiz

    İsim  Yaş  Maaş Departman
0    Ali   25  3000        IT
1  Betül   30  4000        HR
2  Cemal   35  5000        IT
3  Deniz   28  3500   Finance
4   Elif   32  4500        HR

In [187]:
df_dolu = df.fillna(0)
df_dolu

    İsim  Yaş  Maaş Departman
0    Ali   25  3000        IT
1  Betül   30  4000        HR
2  Cemal   35  5000        IT
3  Deniz   28  3500   Finance
4   Elif   32  4500        HR

In [188]:
# sütun bazında doldurma
df_dolu = df.fillna({'Ad': 'Bilinmiyor', 'Yaş': 30, 'Maaş': 3000})
df_dolu

    İsim  Yaş  Maaş Departman
0    Ali   25  3000        IT
1  Betül   30  4000        HR
2  Cemal   35  5000        IT
3  Deniz   28  3500   Finance
4   Elif   32  4500        HR

In [189]:
df_dolu = df.ffill() # yukardaki değer ile doldur
df_dolu

    İsim  Yaş  Maaş Departman
0    Ali   25  3000        IT
1  Betül   30  4000        HR
2  Cemal   35  5000        IT
3  Deniz   28  3500   Finance
4   Elif   32  4500        HR

In [190]:
df_dolu = df.bfill() # aşağdaki değer ile doldur
df_dolu

    İsim  Yaş  Maaş Departman
0    Ali   25  3000        IT
1  Betül   30  4000        HR
2  Cemal   35  5000        IT
3  Deniz   28  3500   Finance
4   Elif   32  4500        HR

In [191]:
# interpolasyon (ara değer tahminlemesi)
df_dolu = df.interpolate(method='linear')
df_dolu

C:\Users\İlyas\AppData\Local\Temp\ipykernel_12384\830235919.py:2: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df_dolu = df.interpolate(method='linear')

    İsim  Yaş  Maaş Departman
0    Ali   25  3000        IT
1  Betül   30  4000        HR
2  Cemal   35  5000        IT
3  Deniz   28  3500   Finance
4   Elif   32  4500        HR

In [192]:
df = pd.DataFrame({
    'Ad': ['Ali', 'Betül', 'Cemal'],
    'Yaş': ['25', '30', '35'],
    'Maaş': [3000, 4000, 5000],
    'Tarih': ['2020-01-15', '2020-02-20', '2020-03-10']
})
df

      Ad Yaş  Maaş       Tarih
0    Ali  25  3000  2020-01-15
1  Betül  30  4000  2020-02-20
2  Cemal  35  5000  2020-03-10

In [193]:
df.dtypes

Ad       object
Yaş      object
Maaş      int64
Tarih    object
dtype: object

In [194]:
# veri tiği dönüştürme
df['Yaş'] = df['Yaş'].astype(int)
df['Maaş'] = df['Maaş'].astype(float)
df['Tarih'] = pd.to_datetime(df['Tarih'])

In [195]:
df.dtypes

Ad               object
Yaş               int64
Maaş            float64
Tarih    datetime64[ns]
dtype: object

In [196]:
# alternatif
df = df.astype({'Yaş': 'int', 'Maaş': 'float'})

In [197]:
df = pd.DataFrame({
    'Ad': ['Ali', 'Betül', 'Ali', 'Cemal', 'Betül'],
    'Yaş': [25, 30, 25, 35, 30]
})

In [198]:
# çoğaltılmış satırları göster
df[df.duplicated()]

      Ad  Yaş
2    Ali   25
4  Betül   30

In [199]:
df_benzersiz = df.drop_duplicates(subset = ['Ad'])
df_benzersiz

      Ad  Yaş
0    Ali   25
1  Betül   30
3  Cemal   35

In [200]:
# benzersiz satır sayısı
len(df) -len(df_benzersiz)

2

In [201]:
# isim değiştirme
df = pd.DataFrame({
    'Ad': ['Ali', 'Betül', 'Cemal'],
    'Yaş': [25, 30, 35], 
    'Maaş': [3000, 4000, 5000]
})

In [202]:
df_yeni = df.rename(columns = {'Ad': 'İsim', 'Yaş': 'Yaş (Yıl)'})
df_yeni

    İsim  Yaş (Yıl)  Maaş
0    Ali         25  3000
1  Betül         30  4000
2  Cemal         35  5000

In [203]:
# satır indexlerini değiştirme
df_yeni = df.rename(index = {0: 'Kimlik1', 1: 'Kimlik2', 2: 'Kimlik3'})
df_yeni

            Ad  Yaş  Maaş
Kimlik1    Ali   25  3000
Kimlik2  Betül   30  4000
Kimlik3  Cemal   35  5000

In [204]:
# İnplace değiştirme (orjinal df i değiştirir)
df.rename(columns = {'Ad': 'İsim'}, inplace = True)
df

    İsim  Yaş  Maaş
0    Ali   25  3000
1  Betül   30  4000
2  Cemal   35  5000

In [205]:
# yeni sütun ekleme
df['Yaş_Kategori'] = df['Yaş'].apply( lambda x: 'Genç' if x < 30 else 'Yaşlı')
df

    İsim  Yaş  Maaş Yaş_Kategori
0    Ali   25  3000         Genç
1  Betül   30  4000        Yaşlı
2  Cemal   35  5000        Yaşlı

In [206]:
# Basit hesaplama
df['Maaş x 12'] = df['Maaş'] * 12
df

    İsim  Yaş  Maaş Yaş_Kategori  Maaş x 12
0    Ali   25  3000         Genç      36000
1  Betül   30  4000        Yaşlı      48000
2  Cemal   35  5000        Yaşlı      60000

In [207]:
# fonksiyon ile 
def vergi_hesapla(maas):
    if maas > 4000:
        return maas * 0.15
    else:
        return maas * 0.10

In [208]:
df['Vergi'] = df['Maaş'].apply(vergi_hesapla)
df

    İsim  Yaş  Maaş Yaş_Kategori  Maaş x 12  Vergi
0    Ali   25  3000         Genç      36000  300.0
1  Betül   30  4000        Yaşlı      48000  400.0
2  Cemal   35  5000        Yaşlı      60000  750.0

In [209]:
# sütun silme
df_yeni = df.drop(['Vergi', 'Maaş x 12'], axis = 1)
df_yeni

    İsim  Yaş  Maaş Yaş_Kategori
0    Ali   25  3000         Genç
1  Betül   30  4000        Yaşlı
2  Cemal   35  5000        Yaşlı

In [210]:
# inplace silme
df.drop('Vergi', axis=1, inplace=True)
df

    İsim  Yaş  Maaş Yaş_Kategori  Maaş x 12
0    Ali   25  3000         Genç      36000
1  Betül   30  4000        Yaşlı      48000
2  Cemal   35  5000        Yaşlı      60000

In [211]:
# satır silme
df_yeni = df.drop(0)
df_yeni

    İsim  Yaş  Maaş Yaş_Kategori  Maaş x 12
1  Betül   30  4000        Yaşlı      48000
2  Cemal   35  5000        Yaşlı      60000

In [212]:
df_yeni = df.drop([0, 2])
df_yeni

    İsim  Yaş  Maaş Yaş_Kategori  Maaş x 12
1  Betül   30  4000        Yaşlı      48000

In [213]:
# satır sütun dönüştürme
df = pd.DataFrame({
'Ad': ['Ali', 'Betül', 'Cemal'],
'Yaş': [25, 30, 35],
'Maaş': [3000, 4000, 5000]
})

In [214]:
#satır ve sütunları değiştirme (transpose)
df_T = df.T
df_T

         0      1      2
Ad     Ali  Betül  Cemal
Yaş     25     30     35
Maaş  3000   4000   5000

In [215]:
#  set index (bir sütunu indeks yap)
df_indexed = df.set_index('Ad')
df_indexed

       Yaş  Maaş
Ad
Ali     25  3000
Betül   30  4000
Cemal   35  5000

In [216]:
df_reset = df_indexed.reset_index()
df_reset

      Ad  Yaş  Maaş
0    Ali   25  3000
1  Betül   30  4000
2  Cemal   35  5000

In [217]:
df_sirali = df[['Maaş', 'Yaş', 'Ad']]
df_sirali

   Maaş  Yaş     Ad
0  3000   25    Ali
1  4000   30  Betül
2  5000   35  Cemal

In [218]:
# Değerleri eşleştirme (Mapping)
haritalama = {25: 'Genç', 30: 'Orta', 35: 'Yaşlı'}
df['Yaş_Grubu'] = df['Yaş'].map(haritalama)
df

      Ad  Yaş  Maaş Yaş_Grubu
0    Ali   25  3000      Genç
1  Betül   30  4000      Orta
2  Cemal   35  5000     Yaşlı

In [219]:
# kategorik veriler
df = pd.DataFrame({
    'Ad': ['Ali', 'Betül', 'Cemal', 'Deniz'],
    'Bölge': ['Doğu', 'Batı', 'Doğu', 'Merkez']
})
df

      Ad   Bölge
0    Ali    Doğu
1  Betül    Batı
2  Cemal    Doğu
3  Deniz  Merkez

In [220]:
# kategorik veri oluşturma 
df['Bölge'] = pd.Categorical(df['Bölge'])
df
print(df.dtypes)

Ad         object
Bölge    category
dtype: object

In [221]:
df['Bölge'] = pd.Categorical(df['Bölge'], categories = ['Doğu', 'Batı', 'Merkez'], ordered = False)

In [222]:
df

      Ad   Bölge
0    Ali    Doğu
1  Betül    Batı
2  Cemal    Doğu
3  Deniz  Merkez

In [223]:
df['Bölge'].dtype

CategoricalDtype(categories=['Doğu', 'Batı', 'Merkez'], ordered=False, categories_dtype=object)

In [224]:
df['Bölge'].cat.categories

Index(['Doğu', 'Batı', 'Merkez'], dtype='object')

In [225]:
df_dummies = pd.get_dummies(df[['Bölge']])
df_dummies

   Bölge_Doğu  Bölge_Batı  Bölge_Merkez
0        True       False         False
1       False        True         False
2        True       False         False
3       False       False          True

In [226]:
# GrupBy ve agregasyon

df = pd.DataFrame({
    'Departman': ['IT', 'HR', 'IT', 'Finance', 'HR', 'IT'],
    'Ad': ['Ali', 'Betül', 'Cemal', 'Deniz', 'Elif', 'Fatih'],
    'Maaş': [3000, 4000, 5000, 3500, 4500, 5500],
    'Yaş': [25, 30, 35, 28, 32, 26]
})
df

  Departman     Ad  Maaş  Yaş
0        IT    Ali  3000   25
1        HR  Betül  4000   30
2        IT  Cemal  5000   35
3   Finance  Deniz  3500   28
4        HR   Elif  4500   32
5        IT  Fatih  5500   26

In [227]:
# departman bazında gruplama
gruplar = df.groupby('Departman')
gruplar

In [228]:
for ad, grup in gruplar:
    print(ad)
    print(grup)

Finance
  Departman     Ad  Maaş  Yaş
3   Finance  Deniz  3500   28
HR
  Departman     Ad  Maaş  Yaş
1        HR  Betül  4000   30
4        HR   Elif  4500   32
IT
  Departman     Ad  Maaş  Yaş
0        IT    Ali  3000   25
2        IT  Cemal  5000   35
5        IT  Fatih  5500   26

In [229]:
len(gruplar)

3

In [230]:
# grup bilgisi
gruplar.groups

{'Finance': [3], 'HR': [1, 4], 'IT': [0, 2, 5]}

In [231]:
# agregasyon fonksiyonları
print(df.groupby('Departman')['Maaş'].max())
print(df.groupby('Departman')['Maaş'].count())
print(df.groupby('Departman')['Maaş'].std())
print(df.groupby('Departman')['Maaş'].first())
print(df.groupby('Departman')['Maaş'].last())

Departman
Finance    3500
HR         4500
IT         5500
Name: Maaş, dtype: int64
Departman
Finance    1
HR         2
IT         3
Name: Maaş, dtype: int64
Departman
Finance            NaN
HR          353.553391
IT         1322.875656
Name: Maaş, dtype: float64
Departman
Finance    3500
HR         4000
IT         3000
Name: Maaş, dtype: int64
Departman
Finance    3500
HR         4500
IT         5500
Name: Maaş, dtype: int64

In [232]:
# çoklu agregasyon
ozet = df.groupby('Departman')['Maaş'].agg(['sum', 'mean', 'count', 'std'])
ozet

             sum    mean  count          std
Departman
Finance     3500  3500.0      1          NaN
HR          8500  4250.0      2   353.553391
IT         13500  4500.0      3  1322.875656

In [233]:
def aralık(x):
    return x.max() -x.min()
df.groupby('Departman')['Maaş'].agg(aralık)

Departman
Finance       0
HR          500
IT         2500
Name: Maaş, dtype: int64

In [234]:
# birden fazla sütun ile guruplama
df = pd.DataFrame({
'Departman': ['IT', 'HR', 'IT', 'Finance', 'HR', 'IT'],
'Unvan': ['Junior', 'Manager', 'Senior', 'Manager', 'Manager', 'Senior'],
'Maaş': [3000, 4000, 5000, 3500, 4500, 5500]
})
df

  Departman    Unvan  Maaş
0        IT   Junior  3000
1        HR  Manager  4000
2        IT   Senior  5000
3   Finance  Manager  3500
4        HR  Manager  4500
5        IT   Senior  5500

In [235]:
# departman ve unvan bazında
ozet = df.groupby(['Departman', 'Unvan'])['Maaş'].agg(['sum', 'mean', 'count'])
ozet

                     sum    mean  count
Departman Unvan
Finance   Manager   3500  3500.0      1
HR        Manager   8500  4250.0      2
IT        Junior    3000  3000.0      1
          Senior   10500  5250.0      2

In [236]:
# pivotlamak
pivot = df.pivot_table(
    values = 'Maaş', 
    index = 'Departman',
    columns = 'Unvan',
    aggfunc= 'mean'
)

In [237]:
pivot

Unvan      Junior  Manager  Senior
Departman
Finance       NaN   3500.0     NaN
HR            NaN   4250.0     NaN
IT         3000.0      NaN  5250.0

In [238]:
df = pd.DataFrame({
'Departman': ['IT', 'IT', 'HR', 'HR'],
'Ad': ['Ali', 'Betül', 'Cemal', 'Deniz'],
'Maaş': [3000, 5000, 4000, 4500]
})

In [239]:
df['Sapma'] = df.groupby('Departman')['Maaş'].transform( lambda x: x - x.mean())

In [240]:
df

  Departman     Ad  Maaş   Sapma
0        IT    Ali  3000 -1000.0
1        IT  Betül  5000  1000.0
2        HR  Cemal  4000  -250.0
3        HR  Deniz  4500   250.0

In [241]:
# birleştirme işlemleri
df1 = pd.DataFrame({
    'Ad': ['Ali', 'Betül'],
    'Yaş': [25, 30]
})
df2 = pd.DataFrame({
    'Ad': ['cemal', 'Deniz'],
    'Yaş': [35, 28]
})
# satır olarak birleştirme
sonuc = pd.concat([df1, df2], ignore_index=True)
sonuc

      Ad  Yaş
0    Ali   25
1  Betül   30
2  cemal   35
3  Deniz   28

In [242]:
# sütun olarak birleştirme (dikey)
sonuc = pd.concat([df1, df2], axis=1)
sonuc

      Ad  Yaş     Ad  Yaş
0    Ali   25  cemal   35
1  Betül   30  Deniz   28

In [243]:
sonuc = pd.concat([df1, df2], keys = ['Grup1', 'Grup2'])
sonuc

            Ad  Yaş
Grup1 0    Ali   25
      1  Betül   30
Grup2 0  cemal   35
      1  Deniz   28

In [244]:
# join (index bazlı)
df1 = pd.DataFrame({
    'Ad': ['Ali', 'Betül', 'Cemal'],
    'Yaş': [25, 30, 35]
}, index = ['ID1', 'ID2', 'ID3'])

In [245]:
df2 = pd.DataFrame({
    'Maaş': [3000, 4000, 5000]
}, index = ['ID1', 'ID2', 'ID3'])

In [246]:
# index bazında birleştirme
sonuc = df1.join(df2)
sonuc

        Ad  Yaş  Maaş
ID1    Ali   25  3000
ID2  Betül   30  4000
ID3  Cemal   35  5000

In [247]:
# apply ve vectorize
df = pd.DataFrame({
    'İsim': ['Ali', 'Betül', 'Cemal'],
    'Yaş': [25, 30, 35],
    'Maaş': [3000, 4000, 5000]
})

In [248]:
def yaş_kategorisi(row):
    if row['Yaş'] < 30:
        return 'Genç'
    else:
        return 'Yaşlı'
    
df['Kategori'] = df.apply(yaş_kategorisi, axis=1)
df

    İsim  Yaş  Maaş Kategori
0    Ali   25  3000     Genç
1  Betül   30  4000    Yaşlı
2  Cemal   35  5000    Yaşlı

In [249]:
def  maaş_vergisi(maas):
    return maas * 0.15 if maas > 4000 else maas * 0.10

df['Vergi'] = df['Maaş'].apply(maaş_vergisi)

In [250]:
df

    İsim  Yaş  Maaş Kategori  Vergi
0    Ali   25  3000     Genç  300.0
1  Betül   30  4000    Yaşlı  400.0
2  Cemal   35  5000    Yaşlı  750.0

In [251]:
df['Maaş_2x'] = df['Maaş'].apply(lambda x: x*2)
df

    İsim  Yaş  Maaş Kategori  Vergi  Maaş_2x
0    Ali   25  3000     Genç  300.0     6000
1  Betül   30  4000    Yaşlı  400.0     8000
2  Cemal   35  5000    Yaşlı  750.0    10000

In [252]:
# string işlemler

df = pd.DataFrame({
    'İsim': ['ali', 'BETÜL', 'Cemal', 'deniz çakmak'],
    'Email': ['ali@example.com', 'betul@example.com', 'cemal@example.com', 'deniz@example.com']
})
df

           İsim              Email
0           ali    ali@example.com
1         BETÜL  betul@example.com
2         Cemal  cemal@example.com
3  deniz çakmak  deniz@example.com

In [253]:
#Büyük harf
df['isim_upper'] = df['İsim'].str.upper()
df

           İsim              Email    isim_upper
0           ali    ali@example.com           ALI
1         BETÜL  betul@example.com         BETÜL
2         Cemal  cemal@example.com         CEMAL
3  deniz çakmak  deniz@example.com  DENIZ ÇAKMAK

In [254]:
# küçük harf

df['İsim_lower'] = df['İsim'].str.lower()
df

           İsim              Email    isim_upper    İsim_lower
0           ali    ali@example.com           ALI           ali
1         BETÜL  betul@example.com         BETÜL         betül
2         Cemal  cemal@example.com         CEMAL         cemal
3  deniz çakmak  deniz@example.com  DENIZ ÇAKMAK  deniz çakmak

In [255]:
# Başharfi büyüt
df['İsim_title'] = df['İsim'].str.title()
df

           İsim              Email    isim_upper    İsim_lower    İsim_title
0           ali    ali@example.com           ALI           ali           Ali
1         BETÜL  betul@example.com         BETÜL         betül         Betül
2         Cemal  cemal@example.com         CEMAL         cemal         Cemal
3  deniz çakmak  deniz@example.com  DENIZ ÇAKMAK  deniz çakmak  Deniz Çakmak

In [256]:
# uzunluk 
df['isim_uzunluğu'] = df['İsim'].str.len()
df

,İsim,Email,isim_upper,İsim_lower,İsim_title,isim_uzunluğu
0,ali,ali@example.com,ALI,ali,Ali,3
1,BETÜL,betul@example.com,BETÜL,betül,Betül,5
2,Cemal,cemal@example.com,CEMAL,cemal,Cemal,5
3,deniz çakmak,deniz@example.com,DENIZ ÇAKMAK,deniz çakmak,Deniz Çakmak,12

In [257]:
# İçeriyor
df['Ali_içeriyor'] = df['İsim'].str.contains('ali', case=False)
print(df)

# Parça çıkar
df['Alan'] = df['Email'].str.extract(r'(.+)@', expand=False)
print(df)

# Böl (Split)
df[['Ad', 'Soyad']] = df['İsim'].str.split(expand=True)
print(df)

# Değiştir
df['İsim_Temiz'] = df['İsim'].str.replace('ç', 'c')
print(df)

# Başlangıç/bitiş kontrol
df['com_ile_bitis'] = df['Email'].str.endswith('.com')
print(df)

           İsim              Email    isim_upper    İsim_lower    İsim_title  \
0           ali    ali@example.com           ALI           ali           Ali
1         BETÜL  betul@example.com         BETÜL         betül         Betül
2         Cemal  cemal@example.com         CEMAL         cemal         Cemal
3  deniz çakmak  deniz@example.com  DENIZ ÇAKMAK  deniz çakmak  Deniz Çakmak

   isim_uzunluğu  Ali_içeriyor
0              3          True
1              5         False
2              5         False
3             12         False
           İsim              Email    isim_upper    İsim_lower    İsim_title  \
0           ali    ali@example.com           ALI           ali           Ali
1         BETÜL  betul@example.com         BETÜL         betül         Betül
2         Cemal  cemal@example.com         CEMAL         cemal         Cemal
3  deniz çakmak  deniz@example.com  DENIZ ÇAKMAK  deniz çakmak  Deniz Çakmak

   isim_uzunluğu  Ali_içeriyor   Alan
0              3          True    ali
1              5         False  betul
2              5         False  cemal
3             12         False  deniz
           İsim              Email    isim_upper    İsim_lower    İsim_title  \
0           ali    ali@example.com           ALI           ali           Ali
1         BETÜL  betul@example.com         BETÜL         betül         Betül
2         Cemal  cemal@example.com         CEMAL         cemal         Cemal
3  deniz çakmak  deniz@example.com  DENIZ ÇAKMAK  deniz çakmak  Deniz Çakmak

   isim_uzunluğu  Ali_içeriyor   Alan     Ad   Soyad
0              3          True    ali    ali    None
1              5         False  betul  BETÜL    None
2              5         False  cemal  Cemal    None
3             12         False  deniz  deniz  çakmak
           İsim              Email    isim_upper    İsim_lower    İsim_title  \
0           ali    ali@example.com           ALI           ali           Ali
1         BETÜL  betul@example.com         BETÜL         betül         Betül
2         Cemal  cemal@example.com         CEMAL         cemal         Cemal
3  deniz çakmak  deniz@example.com  DENIZ ÇAKMAK  deniz çakmak  Deniz Çakmak

   isim_uzunluğu  Ali_içeriyor   Alan     Ad   Soyad    İsim_Temiz
0              3          True    ali    ali    None           ali
1              5         False  betul  BETÜL    None         BETÜL
2              5         False  cemal  Cemal    None         Cemal
3             12         False  deniz  deniz  çakmak  deniz cakmak
           İsim              Email    isim_upper    İsim_lower    İsim_title  \
0           ali    ali@example.com           ALI           ali           Ali
1         BETÜL  betul@example.com         BETÜL         betül         Betül
2         Cemal  cemal@example.com         CEMAL         cemal         Cemal
3  deniz çakmak  deniz@example.com  DENIZ ÇAKMAK  deniz çakmak  Deniz Çakmak

   isim_uzunluğu  Ali_içeriyor   Alan     Ad   Soyad    İsim_Temiz  \
0              3          True    ali    ali    None           ali
1              5         False  betul  BETÜL    None         BETÜL
2              5         False  cemal  Cemal    None         Cemal
3             12         False  deniz  deniz  çakmak  deniz cakmak

   com_ile_bitis
0           True
1           True
2           True
3           True

In [258]:
df = pd.DataFrame({
    'İsim': ['Ali', 'Betül', 'Cemal', 'Deniz'],
    'Yaş': [25, 30, 35, 28],
    'Maaş': [3000, 4000, 5000, 3500]
})

In [259]:
kosullar = [ df['Yaş'] < 26, (df['Yaş'] >= 26 ) & (df['Yaş'] < 31), df['Yaş'] >= 31]
secenekler = ['Çok Genç', 'Genç', 'Yaşlı']

df['Yaş'] = pd.to_numeric(df['Yaş'], errors = 'coerce')
df['Yaş_Grubu'] = np.select(kosullar, secenekler, default='Bilinmiyor')
df

    İsim  Yaş  Maaş Yaş_Grubu
0    Ali   25  3000  Çok Genç
1  Betül   30  4000      Genç
2  Cemal   35  5000     Yaşlı
3  Deniz   28  3500      Genç

In [260]:
# pd.cut

df['Yaş_bin'] = pd.cut(df['Yaş'], bins=[0, 26, 31, 100], labels=['Çok Genç', 'Genç', 'Yaşlı'])
df

    İsim  Yaş  Maaş Yaş_Grubu   Yaş_bin
0    Ali   25  3000  Çok Genç  Çok Genç
1  Betül   30  4000      Genç      Genç
2  Cemal   35  5000     Yaşlı     Yaşlı
3  Deniz   28  3500      Genç      Genç

In [262]:
# pd.qcut
df['Maaş_Quartile'] = pd.qcut(df['Maaş'], q=3, 
                              labels=['Düşük', 'Orta', 'Yüksek'])
df

    İsim  Yaş  Maaş Yaş_Grubu   Yaş_bin Maaş_Quartile
0    Ali   25  3000  Çok Genç  Çok Genç         Düşük
1  Betül   30  4000      Genç      Genç          Orta
2  Cemal   35  5000     Yaşlı     Yaşlı        Yüksek
3  Deniz   28  3500      Genç      Genç         Düşük